name: Build and Deploy to GCP VM

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mathango-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mathango-app:latest

      - name: SSH into GCP VM and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/mathango-app:latest
            docker stop mathango-app || true
            docker rm mathango-app || true
            docker run -d -p 8000:8000 \
              --name mathango-app \
              -e PORT=${{ secrets.ENV_PORT }} \
              -e MONGO_URI=${{ secrets.ENV_MONGO_URI }} \
              -e REDIS_USERNAME=${{ secrets.ENV_REDIS_USERNAME }} \
              -e REDIS_PASSWORD=${{ secrets.ENV_REDIS_PASSWORD }} \
              -e REDIS_SOCKET=${{ secrets.ENV_REDIS_SOCKET }} \
              -e REDIS_PORT=${{ secrets.ENV_REDIS_PORT }} \
              ${{ secrets.DOCKER_USERNAME }}/mathango-app:latest
