name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

     
      - run: npm run dev

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.59.60.195 >> ~/.ssh/known_hosts

      - name: Rsync Deployment to GCP
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /var/www/my-app/
          remote_host: 34.59.60.195
          remote_user: vbg3008  # typically 'vignesh', 'ubuntu', or a GCP user
          remote_key: "${{ secrets.GCP_SSH_KEY }}"
